/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package megacasting.view;

import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author theodore
 */
public class AccueilForm extends javax.swing.JPanel {

    private MainJFrame mainJFrame;

    public AccueilForm(MainJFrame mainJFrame) {
        this.mainJFrame = mainJFrame;
//        this.mainJFrame.setExtendedState(this.mainJFrame.MAXIMIZED_BOTH);
        initComponents();
        
        
    }
    
    /**
     * Creates new form AccueilForm
     */
    public AccueilForm() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonParams = new javax.swing.JButton();
        buttonSociete = new javax.swing.JButton();
        buttonOffre = new javax.swing.JButton();
        buttonStatistique = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(1020, 750));

        buttonParams.setText("Paramètres");
        buttonParams.setPreferredSize(new java.awt.Dimension(1020, 50));
        buttonParams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonParamsActionPerformed(evt);
            }
        });

        buttonSociete.setText("Société");
        buttonSociete.setPreferredSize(new java.awt.Dimension(1020, 50));
        buttonSociete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSocieteActionPerformed(evt);
            }
        });

        buttonOffre.setText("Offre");
        buttonOffre.setPreferredSize(new java.awt.Dimension(1020, 50));
        buttonOffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOffreActionPerformed(evt);
            }
        });

        buttonStatistique.setText("Statistique");
        buttonStatistique.setPreferredSize(new java.awt.Dimension(1020, 50));
        buttonStatistique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStatistiqueActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Rod", 0, 48)); // NOI18N
        jLabel1.setText("            MegaCasting");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonSociete, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
                        .addComponent(buttonOffre, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(buttonStatistique, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(buttonParams, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSociete, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOffre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStatistique, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonParams, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStatistiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStatistiqueActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainJFrame.mainPanel.getLayout();
        cl.show(mainJFrame.mainPanel, "statistiqueCard");
    }//GEN-LAST:event_buttonStatistiqueActionPerformed

    private void buttonOffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOffreActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainJFrame.mainPanel.getLayout();
        cl.show(mainJFrame.mainPanel, "offreCard");
    }//GEN-LAST:event_buttonOffreActionPerformed

    private void buttonSocieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSocieteActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainJFrame.mainPanel.getLayout();
        cl.show(mainJFrame.mainPanel, "societeCard");
    }//GEN-LAST:event_buttonSocieteActionPerformed

    private void buttonParamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonParamsActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainJFrame.mainPanel.getLayout();
        cl.show(mainJFrame.mainPanel, "paramsCard");
    }//GEN-LAST:event_buttonParamsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOffre;
    private javax.swing.JButton buttonParams;
    private javax.swing.JButton buttonSociete;
    private javax.swing.JButton buttonStatistique;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
