/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package megacasting.view;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import megacasting.MegaCasting;
import megacasting.dao.AdresseDAO;
import megacasting.dao.AnnonceurDAO;
import megacasting.dao.DomaineDAO;
import megacasting.dao.MetierDAO;
import megacasting.dao.OffreDAO;
import megacasting.dao.TypeContratDAO;
import megacasting.entite.Adresse;
import megacasting.entite.Annonceur;
import megacasting.entite.Domaine;
import megacasting.entite.Metier;
import megacasting.entite.Offre;
import megacasting.entite.TypeContrat;

/**
 *
 * @author theodore
 */
public class MainJFrame extends javax.swing.JFrame {

    private AccueilForm accueilForm;
    private AdresseForm adresseForm;
    private AnnonceurForm annonceurForm;
    private DiffuseurForm diffuseurForm;
    private OffreForm offreForm;
    private SocieteForm societeForm;
    private ParamsForm paramsForm;
    private StatistiqueForm statistiqueForm;
    
    protected Connection cnx;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
            initComponents();      
        MegaCasting.loadDriver();
        String url = "jdbc:jtds:sqlserver://localhost:1433/MegaCastingCL";
        
        try {
            
            cnx = DriverManager.getConnection(url, "sa", "not24get");
           
            loadCardLayout();
        
            CardLayout cl = (CardLayout) mainPanel.getLayout();
            cl.show(mainPanel, "accueilCard");      
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception ex) {
            ex.printStackTrace();
        } 
    }

    private void loadCardLayout()
    {
        // Accueil
        accueilForm = new AccueilForm(this);
        mainPanel.add(accueilForm, "accueilCard");
        // Adresse
        adresseForm = new AdresseForm(this);
        mainPanel.add(adresseForm, "adresseCard");
        // Annonceur
        annonceurForm = new AnnonceurForm(this);
        mainPanel.add(annonceurForm, "annonceurCard");
        // Diffuseur
        diffuseurForm = new DiffuseurForm(this);
        mainPanel.add(diffuseurForm, "diffuseurCard");
        // Offre
        offreForm = new OffreForm(this);
        mainPanel.add(offreForm, "offreCard");
        // Paramètres
        paramsForm = new ParamsForm(this);
        mainPanel.add(paramsForm, "paramsCard");
        // Societe
        societeForm = new SocieteForm(this);
        mainPanel.add(societeForm, "societeCard");
        // Statistique
        statistiqueForm = new StatistiqueForm(this);
        mainPanel.add(statistiqueForm, "statistiqueCard");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(589, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        mainPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (cnx != null) {
            try {
                cnx.close();
            } catch (SQLException ex){

            }
        }
    }//GEN-LAST:event_formWindowClosing

    protected int affichagePopUpValidation (String contenu, String titre){
        JOptionPane option = new JOptionPane();
        int retour = JOptionPane.showConfirmDialog(this,
                     contenu, 
                     titre,
                     JOptionPane.OK_CANCEL_OPTION);
        return retour;
    }
    
    protected void affichagePopUpInfo (String contenu,String titre){
        JOptionPane option = new JOptionPane();
        JOptionPane.showMessageDialog(this,
                     contenu,
                     titre,
                     JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
