/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package megacasting.view;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import megacasting.dao.AnnonceurDAO;
import megacasting.dao.DomaineDAO;
import megacasting.dao.MetierDAO;
import megacasting.dao.OffreDAO;
import megacasting.dao.TypeContratDAO;
import megacasting.entite.Annonceur;
import megacasting.entite.Domaine;
import megacasting.entite.Metier;
import megacasting.entite.Offre;
import megacasting.entite.TypeContrat;

/**
 *
 * @author theodore
 */
public class OffreForm extends javax.swing.JPanel {

    private MainJFrame mainJFrame;
    public enum Erreur {
        ERREUR_INTITULE_VIDE, ERREUR_REFERENCE_VIDE, ERREUR_REFERENCE_INVALIDE, ERREUR_DUREEDIFFUSION_VIDE,
        ERREUR_DATEDEBUTCONTRAT_VIDE, ERREUR_DATEDEBUTCONTRAT_INVALIDE, ERREUR_NBPOSTE_VIDE, ERREUR_LATTITUDE_VIDE,
        ERREUR_LATTITUDE_INVALIDE, ERREUR_LONGITUDE_VIDE, ERREUR_LONGITUDE_INVALIDE, ERREUR_DESCRIPTIONPOSTE_VIDE,
        ERREUR_DESCRIPTIONPROFIL_VIDE, ERREUR_TELEPHONE_VIDE, ERREUR_TELEPHONE_INVALIDE, ERREUR_EMAIL_VIDE, 
        ERREUR_EMAIL_INVALIDE, ERREUR_IDANNONCEUR_VIDE;
    }

    public OffreForm(MainJFrame mainJFrame) {
        this.mainJFrame = mainJFrame;
        initComponents();
        DefaultListModel<Annonceur>annonceurListModel = new DefaultListModel<>();
        annonceurList.setModel(annonceurListModel);
        DefaultListModel<Domaine>domaineListModel = new DefaultListModel<>();
        domaineList.setModel(domaineListModel);
        DefaultListModel<Metier>metierListModel = new DefaultListModel<>();
        metierList.setModel(metierListModel);
        DefaultListModel<TypeContrat>typeContratListModel = new DefaultListModel<>();
        typeContratList.setModel(typeContratListModel);
        DefaultListModel<Offre>offreListModel = new DefaultListModel<>();
        offreList.setModel(offreListModel);
        
        DefaultComboBoxModel<Annonceur>annonceurComboBoxModel = new DefaultComboBoxModel<>();
        annonceurOffreComboBox.setModel(annonceurComboBoxModel);
        DefaultComboBoxModel<Domaine>domaineComboBoxModel = new DefaultComboBoxModel<>();
        domaineOffreComboBox.setModel(domaineComboBoxModel);
        DefaultComboBoxModel<Metier>metierComboBoxModel = new DefaultComboBoxModel<>();
        metierOffreComboBox.setModel(metierComboBoxModel);
        DefaultComboBoxModel<TypeContrat>typeContratComboBoxModel = new DefaultComboBoxModel<>();
        typeContratOffreComboBox.setModel(typeContratComboBoxModel);
        
        this.datePublicationLabel.setVisible(false);
        this.datePublicationDateChooser.setVisible(false);

        
        
        refreshList();
        refreshComboBox();


    }
    

    /**
     * Creates new form offreForm
     */
    public OffreForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        accueilButton = new javax.swing.JButton();
        domaineLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        domaineList = new javax.swing.JList();
        metierLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        metierList = new javax.swing.JList();
        annonceurLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        annonceurList = new javax.swing.JList();
        typeContratLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        typeContratList = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        offreList = new javax.swing.JList();
        intituleLabel = new javax.swing.JLabel();
        intituleTextField = new javax.swing.JTextField();
        referenceLabel = new javax.swing.JLabel();
        referenceTextField = new javax.swing.JTextField();
        datePublicationLabel = new javax.swing.JLabel();
        dureeDiffusionLabel = new javax.swing.JLabel();
        dureeDiffusionSpinner = new javax.swing.JSpinner();
        dateDebutContratLabel = new javax.swing.JLabel();
        nbPosteLabel = new javax.swing.JLabel();
        nbPosteSpinner = new javax.swing.JSpinner();
        lattitudeLabel = new javax.swing.JLabel();
        lattitudeTextField = new javax.swing.JTextField();
        LongitudeLabel = new javax.swing.JLabel();
        longitudeTextField = new javax.swing.JTextField();
        descriptionPosteLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        descriptionPosteTextArea = new javax.swing.JTextArea();
        descriptionProfilLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        descriptionProfilTextArea = new javax.swing.JTextArea();
        telephoneLabel = new javax.swing.JLabel();
        telephoneTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        datePublicationDateChooser = new com.toedter.calendar.JDateChooser();
        dateDebutContratDateChooser = new com.toedter.calendar.JDateChooser();
        domaineOffreLabel = new javax.swing.JLabel();
        metierOffreLabel = new javax.swing.JLabel();
        domaineOffreComboBox = new javax.swing.JComboBox();
        metierOffreComboBox = new javax.swing.JComboBox();
        typeContratOffreLabel = new javax.swing.JLabel();
        annonceurOffreLabel = new javax.swing.JLabel();
        typeContratOffreComboBox = new javax.swing.JComboBox();
        annonceurOffreComboBox = new javax.swing.JComboBox();
        validerOffreButton = new javax.swing.JButton();
        validationLabel = new javax.swing.JLabel();
        effacerOffreButton = new javax.swing.JButton();
        intituleErreurLabel = new javax.swing.JLabel();
        referenceErreurLabel = new javax.swing.JLabel();
        dureeDiffusionErreurLabel = new javax.swing.JLabel();
        dateDebutContratErreurLabel = new javax.swing.JLabel();
        nbPosteErreurLabel = new javax.swing.JLabel();
        lattitudeErreurLabel = new javax.swing.JLabel();
        longitudeErreurLabel = new javax.swing.JLabel();
        descriptionPosteErreurLabel = new javax.swing.JLabel();
        descriptionProfilErreurLabel = new javax.swing.JLabel();
        emailErreurLabel = new javax.swing.JLabel();
        telephoneErreurLabel = new javax.swing.JLabel();
        annonceurErreurLabel = new javax.swing.JLabel();
        reinitialiserButton = new javax.swing.JButton();

        jLabel1.setText("Offre");

        accueilButton.setText("Accueil");
        accueilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accueilButtonActionPerformed(evt);
            }
        });

        domaineLabel.setText("Domaine");

        domaineList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectionDomaine(evt);
            }
        });
        jScrollPane1.setViewportView(domaineList);

        metierLabel.setText("Métier");

        metierList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectionMetier(evt);
            }
        });
        jScrollPane2.setViewportView(metierList);

        annonceurLabel.setText("Annonceurs");

        annonceurList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectionAnnonceur(evt);
            }
        });
        jScrollPane3.setViewportView(annonceurList);

        typeContratLabel.setText("Type de Contrat");

        typeContratList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectionTypeContrat(evt);
            }
        });
        jScrollPane4.setViewportView(typeContratList);

        offreList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectionOffre(evt);
            }
        });
        jScrollPane5.setViewportView(offreList);

        intituleLabel.setText("Intitule");

        referenceLabel.setText("Référence");

        datePublicationLabel.setText("Date de la publication");

        dureeDiffusionLabel.setText("Durée de la diffusion");

        dateDebutContratLabel.setText("Date de début du contrat");

        nbPosteLabel.setText("Nombre de poste(s)");

        lattitudeLabel.setText("Lattitude");

        LongitudeLabel.setText("Longitude");

        descriptionPosteLabel.setText("Description du poste");

        descriptionPosteTextArea.setColumns(20);
        descriptionPosteTextArea.setRows(5);
        jScrollPane6.setViewportView(descriptionPosteTextArea);

        descriptionProfilLabel.setText("Description du profil");

        descriptionProfilTextArea.setColumns(20);
        descriptionProfilTextArea.setRows(5);
        jScrollPane7.setViewportView(descriptionProfilTextArea);

        telephoneLabel.setText("Téléphone");

        emailLabel.setText("Email");

        domaineOffreLabel.setText("Domaine");

        metierOffreLabel.setText("Métier");

        domaineOffreComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domaineOffreComboBoxActionPerformed(evt);
            }
        });

        typeContratOffreLabel.setText("Type de Contrat");

        annonceurOffreLabel.setText("Annonceur");

        validerOffreButton.setText("Valider");
        validerOffreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerOffreButtonActionPerformed(evt);
            }
        });

        effacerOffreButton.setText("Effacer");
        effacerOffreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effacerOffreButtonActionPerformed(evt);
            }
        });

        intituleErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        referenceErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        dureeDiffusionErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        dateDebutContratErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        nbPosteErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        lattitudeErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        longitudeErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        descriptionPosteErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        descriptionProfilErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        emailErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        telephoneErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        annonceurErreurLabel.setForeground(new java.awt.Color(255, 0, 0));

        reinitialiserButton.setText("Réinitialiser");
        reinitialiserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinitialiserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(domaineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(annonceurLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(metierLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeContratLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reinitialiserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(intituleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(referenceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(datePublicationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                                    .addComponent(metierOffreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(domaineOffreLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(dureeDiffusionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateDebutContratLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nbPosteLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(LongitudeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lattitudeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(validationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(metierOffreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(annonceurOffreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(longitudeErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(datePublicationDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dureeDiffusionSpinner)
                                            .addComponent(dateDebutContratDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nbPosteSpinner)
                                            .addComponent(lattitudeTextField)
                                            .addComponent(longitudeTextField)
                                            .addComponent(lattitudeErreurLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nbPosteErreurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dateDebutContratErreurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dureeDiffusionErreurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(referenceErreurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(intituleErreurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(domaineOffreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 123, Short.MAX_VALUE))
                                            .addComponent(intituleTextField)
                                            .addComponent(referenceTextField))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(descriptionProfilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(descriptionPosteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(typeContratOffreComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(descriptionProfilErreurLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(descriptionPosteErreurLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(emailErreurLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(typeContratOffreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(telephoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addGap(35, 35, 35)
                                                                    .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addComponent(annonceurOffreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(annonceurErreurLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(telephoneErreurLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(effacerOffreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validerOffreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accueilButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domaineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(accueilButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(intituleLabel)
                                    .addComponent(intituleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(descriptionPosteLabel)
                                    .addComponent(intituleErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(referenceLabel)
                                    .addComponent(referenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(referenceErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(datePublicationLabel)
                                    .addComponent(datePublicationDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(descriptionPosteErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(descriptionProfilErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dureeDiffusionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dureeDiffusionLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dureeDiffusionErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descriptionProfilLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateDebutContratLabel)
                                    .addComponent(dateDebutContratDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateDebutContratErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nbPosteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nbPosteLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nbPosteErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telephoneLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telephoneErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lattitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lattitudeLabel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lattitudeErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(longitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LongitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(emailErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(longitudeErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(domaineOffreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(domaineOffreLabel)
                            .addComponent(typeContratOffreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeContratOffreLabel))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(metierOffreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(metierOffreLabel)
                            .addComponent(annonceurOffreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(annonceurOffreLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annonceurErreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(effacerOffreButton)
                            .addComponent(validerOffreButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(metierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(annonceurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(typeContratLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(reinitialiserButton))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accueilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accueilButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainJFrame.mainPanel.getLayout();
        cl.show(mainJFrame.mainPanel, "accueilCard");
    }//GEN-LAST:event_accueilButtonActionPerformed

    private void selectionDomaine(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectionDomaine
        // TODO add your handling code here:
        
        Domaine d = (Domaine)domaineList.getSelectedValue();
        
        DefaultListModel model = (DefaultListModel)metierList.getModel();
        model.clear();
        ArrayList<Metier> metiers = MetierDAO.lister(mainJFrame.cnx, d);
        for(Metier m : metiers)
        {
            if(m != null)
            {
                model.addElement(m);
            }
        }
        
        metierList.setModel(model);
        
        
        DefaultListModel modelOffre = (DefaultListModel)offreList.getModel();
        modelOffre.clear();
        ArrayList<Offre> offres = OffreDAO.lister(mainJFrame.cnx, d);

        for(Offre o : offres){
            modelOffre.addElement(o);
        }

        offreList.setModel(modelOffre);
    }//GEN-LAST:event_selectionDomaine

    private void selectionOffre(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectionOffre
        // TODO add your handling code here:
        Offre o = (Offre)offreList.getSelectedValue();
        if(o != null)
        {
            this.intituleTextField.setText(o.getIntitule());
            this.referenceTextField.setText(o.getReference());
            this.datePublicationLabel.setVisible(true);
            this.datePublicationDateChooser.setVisible(true);
            this.datePublicationDateChooser.setDate(o.getDatePublication());
            this.dureeDiffusionSpinner.setValue(o.getDureeDiffusion());
            this.dateDebutContratDateChooser.setDate(o.getDateDebutContrat());
            this.nbPosteSpinner.setValue(o.getNbPoste());
            this.lattitudeTextField.setText(o.getLocalisationLattitude());
            this.longitudeTextField.setText(o.getLocalisationLongitude());
            this.descriptionPosteTextArea.setText(o.getDescriptionPoste());
            this.descriptionProfilTextArea.setText(o.getDescriptionProfil());
            this.telephoneTextField.setText(o.getTelephone());
            this.emailTextField.setText(o.getEmail());
            
            
            this.typeContratOffreComboBox.setSelectedItem(o.getTypeContrat());
            this.domaineOffreComboBox.setSelectedItem(o.getDomaine());
            this.annonceurOffreComboBox.setSelectedItem(o.getAnnonceur());
            this.metierOffreComboBox.setSelectedItem(o.getMetier());

        }
                   
    }//GEN-LAST:event_selectionOffre
    
    private void validerOffreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerOffreButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<Erreur> erreurs = verifFormulaire();
        if(erreurs.isEmpty()) {
            
        String intitule = this.intituleTextField.getText();
        String reference = this.referenceTextField.getText();
        int dureeDiffusion = (int)this.dureeDiffusionSpinner.getValue();
        Date dateDebutContrat = this.dateDebutContratDateChooser.getDate();
        int nbPoste = (int)this.nbPosteSpinner.getValue();
        String lattitude = this.lattitudeTextField.getText();
        String longitude = this.longitudeTextField.getText();
        String descriptionPoste = this.descriptionPosteTextArea.getText();
        String descriptionProfil = this.descriptionProfilTextArea.getText();
        String telephone = this.telephoneTextField.getText();
        String email = this.emailTextField.getText();
        Domaine domaine = (Domaine)this.domaineOffreComboBox.getSelectedItem();
        Metier metier = (Metier)this.metierOffreComboBox.getSelectedItem();
        TypeContrat typeContrat = (TypeContrat)this.typeContratOffreComboBox.getSelectedItem();
        Annonceur annonceur = (Annonceur)this.annonceurOffreComboBox.getSelectedItem();
        

        Offre o = OffreDAO.trouver(mainJFrame.cnx, reference);
        if(o == null)
        {
            try {
                 o = new Offre(intitule,reference,dureeDiffusion,
                        dateDebutContrat,nbPoste,lattitude,longitude,descriptionPoste,descriptionProfil,
                        telephone,email,domaine,metier,typeContrat,annonceur);

                OffreDAO.creer(mainJFrame.cnx,o);
                raz();
                refreshList();
                validationLabel.setText("L'offre a été crée !");
            } catch (Exception e) {
                validationLabel.setText("Une erreur s'est produite lors de la création");
                e.printStackTrace();
            } 
        } else {
            o.setIntitule(intitule);
            o.setReference(reference);
            o.setDureeDiffusion(dureeDiffusion);
            o.setDateDebutContrat(dateDebutContrat);
            o.setNbPoste(nbPoste);
            o.setLocalisationLattitude(lattitude);
            o.setLocalisationLongitude(longitude);
            o.setDescriptionPoste(descriptionPoste);
            o.setDescriptionProfil(descriptionProfil);
            o.setTelephone(telephone);
            o.setEmail(email);
            o.setDomaine(domaine);
            o.setMetier(metier);
            o.setTypeContrat(typeContrat);
            o.setAnnonceur(annonceur);
            try {
                OffreDAO.modifier(mainJFrame.cnx, o);
                raz();
                refreshList();
                validationLabel.setText("L'offre a été modifiée !");
            } catch (Exception ex) {
                validationLabel.setText("Une erreur s'est produite lors de la modification");
            ex.printStackTrace();
            }
        }
        } else {
            affichageErreurs(erreurs);
        }

    }//GEN-LAST:event_validerOffreButtonActionPerformed

    private void effacerOffreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effacerOffreButtonActionPerformed
        // TODO add your handling code here:
        raz();
    }//GEN-LAST:event_effacerOffreButtonActionPerformed

    private void domaineOffreComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domaineOffreComboBoxActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel model = (DefaultComboBoxModel)domaineOffreComboBox.getModel();
        Domaine d = (Domaine)model.getSelectedItem();
        
        ArrayList<Metier>metiers = MetierDAO.lister(mainJFrame.cnx, d);
        DefaultComboBoxModel modelMetier = (DefaultComboBoxModel)metierOffreComboBox.getModel();
        
        modelMetier.removeAllElements();
        
        for( Metier m : metiers) {
            modelMetier.addElement(m);
        }
        
        metierOffreComboBox.setModel(modelMetier);
        
    }//GEN-LAST:event_domaineOffreComboBoxActionPerformed

    private void selectionAnnonceur(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectionAnnonceur
        // TODO add your handling code here:
        
        Annonceur a = (Annonceur)annonceurList.getSelectedValue();
        
        DefaultListModel modelOffre = (DefaultListModel)offreList.getModel();
        modelOffre.clear();
        ArrayList<Offre> offres = OffreDAO.lister(mainJFrame.cnx, a);

        for(Offre o : offres){
            modelOffre.addElement(o);
        }

        offreList.setModel(modelOffre);
    }//GEN-LAST:event_selectionAnnonceur

    private void selectionTypeContrat(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectionTypeContrat
        // TODO add your handling code here:
        
        TypeContrat tc = (TypeContrat)typeContratList.getSelectedValue();
        
        DefaultListModel modelOffre = (DefaultListModel)offreList.getModel();
        modelOffre.clear();
        ArrayList<Offre> offres = OffreDAO.lister(mainJFrame.cnx,tc);
        
        for(Offre o : offres){
            modelOffre.addElement(o);
        }

        offreList.setModel(modelOffre);
    }//GEN-LAST:event_selectionTypeContrat

    private void reinitialiserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinitialiserButtonActionPerformed
        // TODO add your handling code here: 
        
        refreshListOffres();

    }//GEN-LAST:event_reinitialiserButtonActionPerformed

    private void selectionMetier(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectionMetier
        // TODO add your handling code here:
        
        Metier m = (Metier)metierList.getSelectedValue();
        
        DefaultListModel modelOffre = (DefaultListModel)offreList.getModel();
        modelOffre.clear();
        ArrayList<Offre> offres = OffreDAO.lister(mainJFrame.cnx,m);

        for(Offre o : offres){
            modelOffre.addElement(o);
        }

        offreList.setModel(modelOffre);
        
    }//GEN-LAST:event_selectionMetier

    private void raz(){
        this.intituleTextField.setText(null);
        this.referenceTextField.setText(null);
        this.datePublicationLabel.setVisible(false);
        this.datePublicationDateChooser.setVisible(false);
        this.dureeDiffusionSpinner.setValue(0);
        this.dateDebutContratDateChooser.setDate(null);
        this.nbPosteSpinner.setValue(0);
        this.lattitudeTextField.setText(null);
        this.longitudeTextField.setText(null);
        this.descriptionPosteTextArea.setText(null);
        this.descriptionProfilTextArea.setText(null);
        this.telephoneTextField.setText(null);
        this.emailTextField.setText(null);
        
        this.intituleErreurLabel.setText(null);
        this.referenceErreurLabel.setText(null);
        this.dureeDiffusionErreurLabel.setText(null);
        this.dateDebutContratErreurLabel.setText(null);
        this.nbPosteErreurLabel.setText(null);
        this.lattitudeErreurLabel.setText(null);
        this.longitudeErreurLabel.setText(null);
        this.descriptionPosteErreurLabel.setText(null);
        this.descriptionProfilErreurLabel.setText(null);
        this.telephoneErreurLabel.setText(null);
        this.emailErreurLabel.setText(null);
        this.annonceurErreurLabel.setText(null);
        
    }
    
    private void refreshList(){
        refreshListAnnonceurs();
        refreshListDomaines();
        refreshListMetiers();
        refreshListTypeContrat();
        refreshListOffres();
    }
    
    private void refreshListOffres(){
        DefaultListModel model = (DefaultListModel)offreList.getModel();
        model.clear();
        ArrayList<Offre> offres = OffreDAO.lister(mainJFrame.cnx);
        for(Offre o : offres)
        {
            model.addElement(o);
        }
        offreList.setModel(model);
        
    }
    
    private void refreshListAnnonceurs(){
        DefaultListModel model = (DefaultListModel)annonceurList.getModel();
        model.clear();
        ArrayList<Annonceur> annonceurs = AnnonceurDAO.lister(mainJFrame.cnx);
        for(Annonceur a : annonceurs)
        {
            model.addElement(a);
        }
        annonceurList.setModel(model);
        
    }
    
    private void refreshListDomaines(){
        DefaultListModel model = (DefaultListModel)domaineList.getModel();
        model.clear();
        ArrayList<Domaine> domaines = DomaineDAO.lister(mainJFrame.cnx);
        for(Domaine d : domaines)
        {
            model.addElement(d);
        }
        domaineList.setModel(model);
        
    }
    
    private void refreshListMetiers(){
    DefaultListModel model = (DefaultListModel)metierList.getModel();
    model.clear();
    ArrayList<Metier> metiers = MetierDAO.lister(mainJFrame.cnx);
    for(Metier m : metiers)
    {
        model.addElement(m);
    }
    metierList.setModel(model);
        
    }
    
    private void refreshListTypeContrat(){
    DefaultListModel model = (DefaultListModel)typeContratList.getModel();
    model.clear();
    ArrayList<TypeContrat> typeContrats = TypeContratDAO.lister(mainJFrame.cnx);
    for(TypeContrat tc : typeContrats)
    {
        model.addElement(tc);
    }
    typeContratList.setModel(model);
        
    }
    
    private void refreshComboBox () {
        refreshComboBoxAnnonceurs();
        refreshComboBoxDomaines();
        refreshComboBoxTypeContrats();
    }
    
    private void refreshComboBoxAnnonceurs () {
        DefaultComboBoxModel<Annonceur> model = (DefaultComboBoxModel)annonceurOffreComboBox.getModel();
        model.removeAllElements();
        ArrayList<Annonceur> annonceurs = AnnonceurDAO.lister(mainJFrame.cnx);
        for(Annonceur a : annonceurs)
        {
            model.addElement(a);
        }
        annonceurOffreComboBox.setModel(model);
    }
    
    private void refreshComboBoxDomaines() {
        DefaultComboBoxModel<Domaine> model = (DefaultComboBoxModel)domaineOffreComboBox.getModel();
        model.removeAllElements();
        ArrayList<Domaine> domaines = DomaineDAO.lister(mainJFrame.cnx);
        for(Domaine d : domaines)
        {
            model.addElement(d);
        }
        domaineOffreComboBox.setModel(model);
    }
    
    private void refreshComboBoxTypeContrats() {
        DefaultComboBoxModel<TypeContrat> model = (DefaultComboBoxModel)typeContratOffreComboBox.getModel();
        model.removeAllElements();
        ArrayList<TypeContrat> typeContrats = TypeContratDAO.lister(mainJFrame.cnx);
        for(TypeContrat tc : typeContrats)
        {
            model.addElement(tc);
        }
        typeContratOffreComboBox.setModel(model);
    }
    
    private ArrayList verifFormulaire() {

    ArrayList<Erreur> erreurs = new ArrayList();
    
    // Creation d'une erreur si le champ intitule est vide
    if(this.intituleTextField.getText().equals("")) {
        erreurs.add(Erreur.ERREUR_INTITULE_VIDE);
    } else {
        this.intituleErreurLabel.setText(null);
    }
    // Creation d'une erreur si le champ reference est vide
    if(this.referenceTextField.getText().equals("")) {
        erreurs.add(Erreur.ERREUR_REFERENCE_VIDE);
    } else {
        // Creation d'une erreur si le champ reference a été mal saisi
        Boolean verifReference = regexReference(this.referenceTextField.getText());
        if(verifReference != true) {
            erreurs.add(Erreur.ERREUR_REFERENCE_INVALIDE);
        } else {
            this.referenceErreurLabel.setText(null);
        }
    }
    // Creation d'une erreur si la durée de diffusion est égale à 0
    if((int)this.dureeDiffusionSpinner.getValue() == 0) {
        erreurs.add(Erreur.ERREUR_DUREEDIFFUSION_VIDE);        
    } else {
        this.dureeDiffusionErreurLabel.setText(null);
    }
    // Creation d'une erreur si la date de début de contrat est vide 
    if(this.dateDebutContratDateChooser.getDate() ==  null) {
        erreurs.add(Erreur.ERREUR_DATEDEBUTCONTRAT_VIDE);
    } else {
        Date now = new Date();
        // Creation d'une erreur si la date de debut de oontrat est inférieure à celle de publication
        if(this.dateDebutContratDateChooser.getDate().before(now)){
            erreurs.add(Erreur.ERREUR_DATEDEBUTCONTRAT_INVALIDE);
        } else {
            this.dateDebutContratErreurLabel.setText(null);
        }
    }
    // Creation d'une erreur si le nombre de postes est égale à 0
    if((int)this.nbPosteSpinner.getValue() == 0) {
        erreurs.add(Erreur.ERREUR_NBPOSTE_VIDE);
    } else {
        this.nbPosteErreurLabel.setText(null);
    }
    // Creation d'une erreur si la lattitude est vide 
    if(this.lattitudeTextField.getText().equals("")) {
        erreurs.add(Erreur.ERREUR_LATTITUDE_VIDE);
    } else {
        // Creation d'une erreur si la lattitude saisie est incorrect
//        Boolean verifLattitude = regexCoordonnées(this.lattitudeTextField.getText());
//        if(verifLattitude != true) {
//            erreurs.add(Erreur.ERREUR_LATTITUDE_INVALIDE);
//        } else {
            this.lattitudeErreurLabel.setText(null);
//        }
    }
    // Creation d'une erreur si la longitude est vide 
    if(this.longitudeTextField.getText().equals("")) {
        erreurs.add(Erreur.ERREUR_LONGITUDE_VIDE);
    } else {
        // Creation d'une erreur si la longitude saisie est incorrect
//        Boolean verifLongitude = regexCoordonnées(this.longitudeTextField.getText());
//        if(verifLongitude != true ) {
//            erreurs.add(Erreur.ERREUR_LONGITUDE_INVALIDE);
//        } else {
            this.longitudeErreurLabel.setText(null);
//        }
    }
    // Creation d'une erreur si la description de poste est vide 
    if(this.descriptionPosteTextArea.getText().equals("")) {
        erreurs.add(Erreur.ERREUR_DESCRIPTIONPOSTE_VIDE);
    } else {
        this.descriptionPosteErreurLabel.setText(null);
    }
    // Creation d'une erreur si la description du profil est vide
    if(this.descriptionProfilTextArea.getText().equals("")) {
        erreurs.add(Erreur.ERREUR_DESCRIPTIONPROFIL_VIDE);
    } else {
        this.descriptionProfilErreurLabel.setText(null);
    }
    // Creation d'une erreur si le numéro de téléphone est vide
    if(this.telephoneTextField.getText().equals("")) {
        erreurs.add(Erreur.ERREUR_TELEPHONE_VIDE);
    } else {
        // Creation d'une erreur si le numéro de téléphone saisi est incorrect
        Boolean verifTelephone = regexTelephone(this.telephoneTextField.getText());
        if(verifTelephone != true) {
            erreurs.add(Erreur.ERREUR_TELEPHONE_INVALIDE);
        } else {
            this.telephoneErreurLabel.setText(null);
        }
    }
    // Creation d'une erreur si l'email est vide
    if(this.emailTextField.getText().equals("")) {
        erreurs.add(Erreur.ERREUR_EMAIL_VIDE);
    } else {
        // Creation d'une erreur si l'email saisie est incorrect 
        Boolean verifEmail = regexEmail(this.emailTextField.getText());
        if(verifEmail != true) {
            erreurs.add(Erreur.ERREUR_EMAIL_INVALIDE);
        } else {
            this.emailErreurLabel.setText(null);
        }
    }
    // Creation d'une erreur si aucun annonceur à été choisi
    if(this.annonceurOffreComboBox.getSelectedItem() == null) {
        erreurs.add(Erreur.ERREUR_IDANNONCEUR_VIDE);
    } else {
        this.annonceurErreurLabel.setText(null);
    }
    
    return erreurs;
    
    }
    
    private void affichageErreurs (ArrayList<Erreur> erreurs){
        
        for(Erreur erreur : erreurs) {
            switch (erreur) {
                
                case ERREUR_INTITULE_VIDE :             this.intituleErreurLabel.setText("Veuillez saisir un intitulé !");
                                                        break;
                case ERREUR_REFERENCE_VIDE :            this.referenceErreurLabel.setText("Veuillez saisir une référence !");
                                                        break;
                case ERREUR_REFERENCE_INVALIDE :        this.referenceErreurLabel.setText("Veuillez saisir une référence correcte !");
                                                        break;
                case ERREUR_DUREEDIFFUSION_VIDE :       this.dureeDiffusionErreurLabel.setText("Veuillez saisir une durée de diffusion supérieure à 0 !");
                                                        break;
                case ERREUR_DATEDEBUTCONTRAT_VIDE :     this.dateDebutContratErreurLabel.setText("Veuillez saisir une date de début de contrat !");
                                                        break;
                case ERREUR_DATEDEBUTCONTRAT_INVALIDE : this.dateDebutContratErreurLabel.setText("La date saisie est inférieure à celle d\'aujourdh'hui !");
                                                        break;
                case ERREUR_NBPOSTE_VIDE :              this.nbPosteErreurLabel.setText("Veuillez saisir le nombre de postes pour l'offre !");
                                                        break;
                case ERREUR_LATTITUDE_VIDE :            this.lattitudeErreurLabel.setText("Veuillez saisir une lattitude !");
                                                        break;
                case ERREUR_LATTITUDE_INVALIDE :        this.lattitudeErreurLabel.setText("Veuillez saisir une lattitude correcte : 00° 00' N !");
                                                        break;
                case ERREUR_LONGITUDE_VIDE :            this.longitudeErreurLabel.setText("Veuillez saisir une longitude !");
                                                        break;
                case ERREUR_LONGITUDE_INVALIDE :        this.longitudeErreurLabel.setText("Veuillez saisir une longitude correcte : 00° 00' N !");
                                                        break;
                case ERREUR_DESCRIPTIONPOSTE_VIDE :     this.descriptionPosteErreurLabel.setText("Veuillez saisir une description de poste !");
                                                        break;
                case ERREUR_DESCRIPTIONPROFIL_VIDE :    this.descriptionProfilErreurLabel.setText("Veuillez saisir une description de profil !");
                                                        break;
                case ERREUR_TELEPHONE_VIDE :            this.telephoneErreurLabel.setText("Veuillez saisir un numéro de téléphone !");
                                                        break;
                case ERREUR_TELEPHONE_INVALIDE :        this.telephoneErreurLabel.setText("Veuillez saisir une numéro de téléphone de 10 chiffres !");
                                                        break;
                case ERREUR_EMAIL_VIDE :                this.emailErreurLabel.setText("Veuillez saisir un email !");
                                                        break;
                case ERREUR_EMAIL_INVALIDE :            this.emailErreurLabel.setText("Veuillez saisir un email correct !");
                                                        break;
                case ERREUR_IDANNONCEUR_VIDE :          this.annonceurErreurLabel.setText("Veuillez choisir un annonceur pour votre offre !");
                                                        break;
                default : break;
            
            
            }
            
            
            

            
        }
    }
    
    private Boolean regexCoordonnees(String coordonnée) {
        Pattern p = Pattern.compile("^[0-9]{2}° [0-9]{2}' [N-S-E-O]{1}$");
        Matcher m = p.matcher(coordonnée);
        Boolean b = m.matches();
        
        return b;
    }
    
    private Boolean regexReference(String reference) {
        Pattern p = Pattern.compile("^[a-zA-Z0-9_-]+$");
        Matcher m = p.matcher(reference);
        Boolean b = m.matches();
        
        return b;
    }
    
    private Boolean regexTelephone(String telephone) {
        Pattern p = Pattern.compile("^0[1-68]([.-]?[0-9]{2}){4}$");
        Matcher m = p.matcher(telephone);
        Boolean b = m.matches();

        return b;
    }
    
    private Boolean regexEmail(String email) {
        Pattern p = Pattern.compile("^[a-z0-9._-]+@[a-z0-9._-]{2,}\\.[a-z]{2,4}$");
        Matcher m = p.matcher(email);
        Boolean b = m.matches();
        
        return b;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LongitudeLabel;
    private javax.swing.JButton accueilButton;
    private javax.swing.JLabel annonceurErreurLabel;
    private javax.swing.JLabel annonceurLabel;
    private javax.swing.JList annonceurList;
    private javax.swing.JComboBox annonceurOffreComboBox;
    private javax.swing.JLabel annonceurOffreLabel;
    private com.toedter.calendar.JDateChooser dateDebutContratDateChooser;
    private javax.swing.JLabel dateDebutContratErreurLabel;
    private javax.swing.JLabel dateDebutContratLabel;
    private com.toedter.calendar.JDateChooser datePublicationDateChooser;
    private javax.swing.JLabel datePublicationLabel;
    private javax.swing.JLabel descriptionPosteErreurLabel;
    private javax.swing.JLabel descriptionPosteLabel;
    private javax.swing.JTextArea descriptionPosteTextArea;
    private javax.swing.JLabel descriptionProfilErreurLabel;
    private javax.swing.JLabel descriptionProfilLabel;
    private javax.swing.JTextArea descriptionProfilTextArea;
    private javax.swing.JLabel domaineLabel;
    private javax.swing.JList domaineList;
    private javax.swing.JComboBox domaineOffreComboBox;
    private javax.swing.JLabel domaineOffreLabel;
    private javax.swing.JLabel dureeDiffusionErreurLabel;
    private javax.swing.JLabel dureeDiffusionLabel;
    private javax.swing.JSpinner dureeDiffusionSpinner;
    private javax.swing.JButton effacerOffreButton;
    private javax.swing.JLabel emailErreurLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel intituleErreurLabel;
    private javax.swing.JLabel intituleLabel;
    private javax.swing.JTextField intituleTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lattitudeErreurLabel;
    private javax.swing.JLabel lattitudeLabel;
    private javax.swing.JTextField lattitudeTextField;
    private javax.swing.JLabel longitudeErreurLabel;
    private javax.swing.JTextField longitudeTextField;
    private javax.swing.JLabel metierLabel;
    private javax.swing.JList metierList;
    private javax.swing.JComboBox metierOffreComboBox;
    private javax.swing.JLabel metierOffreLabel;
    private javax.swing.JLabel nbPosteErreurLabel;
    private javax.swing.JLabel nbPosteLabel;
    private javax.swing.JSpinner nbPosteSpinner;
    private javax.swing.JList offreList;
    private javax.swing.JLabel referenceErreurLabel;
    private javax.swing.JLabel referenceLabel;
    private javax.swing.JTextField referenceTextField;
    private javax.swing.JButton reinitialiserButton;
    private javax.swing.JLabel telephoneErreurLabel;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextField telephoneTextField;
    private javax.swing.JLabel typeContratLabel;
    private javax.swing.JList typeContratList;
    private javax.swing.JComboBox typeContratOffreComboBox;
    private javax.swing.JLabel typeContratOffreLabel;
    private javax.swing.JLabel validationLabel;
    private javax.swing.JButton validerOffreButton;
    // End of variables declaration//GEN-END:variables
}
