/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package megacasting.view;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import megacasting.dao.TypeContratDAO;
import megacasting.entite.TypeContrat;

/**
 *
 * @author theodore
 */
public class TypeContratForm extends javax.swing.JPanel {

    private MainJFrame mainJFrame;

    public TypeContratForm(MainJFrame mainJFrame) {
        this.mainJFrame = mainJFrame;
        initComponents();
        
        DefaultListModel<TypeContrat> modelListTypeContrat = new DefaultListModel<>();
        ArrayList<TypeContrat> typeContrats = TypeContratDAO.lister(mainJFrame.cnx);

        for (TypeContrat tc : typeContrats) {
            modelListTypeContrat.addElement(tc);
        }
        listTypeContrat.setModel(modelListTypeContrat);
    }
    
    /**
     * Creates new form TypeContratForm
     */
    public TypeContratForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listTypeContrat = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        libelleLabel = new javax.swing.JLabel();
        libelleTextField = new javax.swing.JTextField();
        supprimerButton = new javax.swing.JButton();
        modifierButton = new javax.swing.JButton();
        accueilButton = new javax.swing.JButton();

        listTypeContrat.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listTypeContrat);

        libelleLabel.setText("Libelle : ");

        supprimerButton.setText("Supprimer");
        supprimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerButtonActionPerformed(evt);
            }
        });

        modifierButton.setText("Modifier");
        modifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierButtonActionPerformed(evt);
            }
        });

        accueilButton.setText("Accueil");
        accueilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accueilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(supprimerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(libelleLabel)
                        .addGap(18, 18, 18)
                        .addComponent(libelleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(modifierButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accueilButton)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libelleLabel)
                    .addComponent(libelleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(modifierButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(accueilButton)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supprimerButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supprimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerButtonActionPerformed
        // TODO add your handling code here:
        TypeContrat typeContrat = (TypeContrat) listTypeContrat.getSelectedValue();
        
        TypeContratDAO.supprimer(mainJFrame.cnx, typeContrat);
    }//GEN-LAST:event_supprimerButtonActionPerformed

    private void accueilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accueilButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainJFrame.mainPanel.getLayout();
        cl.show(mainJFrame.mainPanel, "accueilCard");
    }//GEN-LAST:event_accueilButtonActionPerformed

    private void modifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierButtonActionPerformed
        // TODO add your handling code here:
        // On récupère le libelle type contrat
        String libelle = libelleTextField.getText();
        
        TypeContrat typeContrat = TypeContratDAO.trouver(mainJFrame.cnx, libelle);
        
        try {
            // Si il existe -> on le modifie
            if (typeContrat != null) {
                TypeContratDAO.modifier(mainJFrame.cnx, typeContrat);
            }
            // Sinon on le crée
            else {
                typeContrat = TypeContratDAO.creer(mainJFrame.cnx, typeContrat);
                
                DefaultListModel<TypeContrat> modelListTypeContrat = (DefaultListModel<TypeContrat>) listTypeContrat.getModel();
                modelListTypeContrat.addElement(typeContrat);
            }
        } catch (Exception ex) {
                ex.printStackTrace();
        }
        
    }//GEN-LAST:event_modifierButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accueilButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel libelleLabel;
    private javax.swing.JTextField libelleTextField;
    private javax.swing.JList listTypeContrat;
    private javax.swing.JButton modifierButton;
    private javax.swing.JButton supprimerButton;
    // End of variables declaration//GEN-END:variables
}
